import os

# instructions for using this script to get links to ticketing events:

# open chrome, go to the page for Doc Films' season
# open inspect element
# go to the console tab
# enter `copy(articleContext)` -- this copies the variable with all the data from the Logan event database to your clipboard
# paste it into the `ticketing_dict` variable in this script
# edit your `parent_directory` and `output_name` variables if need be (way down at the bottom)
# run the script and you're done!

ticketing_dict = {
    "searchHeaders": [
        "Id",
        "Object Type",
        "Type",
        "Category",
        "Name",
        "Description",
        "Short Description",
        "Start Date",
        "Start Date time",
        "Start Date date",
        "Start Date month",
        "Start Date year",
        "End Date",
        "On Sale Date",
        "Sales Status",
        "Availability",
        "Available Number",
        "Keywords",
        "Additional Info",
        "Group",
        "Image 1",
        "Image 2",
        "thumbnail",
        "Data 1",
        "Data 2",
        "Data 3",
        "Data 4",
        "Data 5",
        "Data 6",
        "Data 7",
        "Data 8",
        "Data 9",
        "Data 10",
        "Data 11",
        "Data 12",
        "Data 13",
        "Data 14",
        "Data 15",
        "Data 16",
        "filter1",
        "filter2",
        "filter3",
        "filter4",
        "filter_parent1",
        "filter_child2",
        "filter_parent2",
        "filter_child1",
        "multifilter1",
        "multifilter2",
        "Organization Short Description",
        "Sales Type",
        "Options",
        "Street",
        "City",
        "Province / State",
        "Postal Code",
        "Country",
        "Longitude",
        "Latitude",
        "Venue ID",
        "Venue Name",
        "Venue Description",
        "Venue Short Description",
        "Venue Group",
        "Venue Data 1",
        "Venue Data 2",
        "Venue Data 3",
        "Venue Data 4",
        "Venue Data 5",
        "Venue Data 6",
        "Venue Data 7",
        "Venue Data 8",
        "Venue Data 9",
        "Venue Data 10",
        "Venue Data 11",
        "Venue Data 12",
        "Venue Type",
        "Series Name",
        "Minimum Price",
        "Maximum Price",
        "Upsell Article",
        "Add-on Article",
        "email",
        "e_address1",
        "e_address2",
        "e_address3",
        "customer_id",
        "tracking_code",
        "twitter_search_term",
        "external_reference_code",
        "access",
        "Venue Organization Id",
        "Meta Description",
        ""
    ],
    "searchNames": [
        "id",
        "object_type",
        "type",
        "category",
        "name",
        "description",
        "short_description",
        "start_date",
        "start_date_time",
        "start_date_date",
        "start_date_month",
        "start_date_year",
        "end_date",
        "on_sale_date",
        "sales_status",
        "availability_status",
        "availability_num",
        "keywords",
        "additional_info",
        "group",
        "image1",
        "image2",
        "thumbnail",
        "data1",
        "data2",
        "data3",
        "data4",
        "data5",
        "data6",
        "data7",
        "data8",
        "data9",
        "data10",
        "data11",
        "data12",
        "data13",
        "data14",
        "data15",
        "data16",
        "filter1",
        "filter2",
        "filter3",
        "filter4",
        "filter_parent1",
        "filter_child2",
        "filter_parent2",
        "filter_child1",
        "multifilter1",
        "multifilter2",
        "organization_short_description",
        "sales_type",
        "options",
        "street",
        "city",
        "state",
        "zip",
        "country",
        "longitude",
        "latitude",
        "venue_id",
        "venue_name",
        "venue_description",
        "venue_short_description",
        "venue_group",
        "venue_data1",
        "venue_data2",
        "venue_data3",
        "venue_data4",
        "venue_data5",
        "venue_data6",
        "venue_data7",
        "venue_data8",
        "venue_data9",
        "venue_data10",
        "venue_data11",
        "venue_data12",
        "venue_type",
        "series_name",
        "min_price",
        "max_price",
        "upsell_article_id",
        "addon_article_id",
        "email",
        "e_address1",
        "e_address2",
        "e_address3",
        "customer_id",
        "tracking_code",
        "twitter_search_term",
        "external_reference_code",
        "access",
        "organization_id",
        "meta_description",
        ""
    ],
    "searchResults": [
        [
            "8409438E-2BE6-4DF9-B696-F01CE7291341",
            "M",
            "Merchandise",
            "",
            "UCArts-Doc Films Quarter Pass",
            "UCArts-Doc Films Quarter Pass",
            "Doc Films Quarter Pass",
            "Wed, Sep 28, 2022 12:00 AM",
            "00:00",
            "28",
            "8",
            "2022",
            "",
            "",
            "S",
            "",
            "",
            "Doc Films",
            "",
            "",
            "/content/Images/autumn-2022-quarter-pass.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [],
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "$40.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ],
        [
            "D8138BBA-0699-4ECA-A2DA-A74576AE0D2C",
            "P",
            "Evening",
            "",
            "UCADF20220927",
            "Diao Yinan&nbsp;| 2014 | Digital | 110m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Black Coal, Thin Ice",
            "Tue, Sep 27, 2022 7:00 PM",
            "19:00",
            "27",
            "8",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/black-coal-thin-ice-2014.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "B8A75D91-2745-4CE9-9A93-406E763F39AA",
            "P",
            "Evening",
            "",
            "UCADF20220928",
            "Jackie Chan&nbsp;| 1985 | DCP | 100m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Police Story",
            "Wed, Sep 28, 2022 7:00 PM",
            "19:00",
            "28",
            "8",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/police-story-1985.jpeg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "CEB2435B-B355-44D8-9720-7EF1A7CBADE4",
            "P",
            "Evening",
            "",
            "UCADF202209292",
            "Lotte Reiniger | 1926 | 35mm | 65m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "The Adventures of Prince Achmed",
            "Thu, Sep 29, 2022 7:00 PM",
            "19:00",
            "29",
            "8",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/the-adventures-of-prince-achmed-1926.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "37B1DAAB-F73A-4A27-9ED7-9771A68B4510",
            "P",
            "Evening",
            "",
            "UCADF20220929",
            "Gil Junger&nbsp;| 1999 | DCP | 97m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "10 Things I Hate About You",
            "Thu, Sep 29, 2022 7:00 PM",
            "19:00",
            "29",
            "8",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/10-things-i-hate-about-you-1999.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "9866C09F-DD73-41B2-943D-F7BA7E4412E5",
            "P",
            "Evening",
            "",
            "UCADF20220930",
            "Satoshi Kon&nbsp;| 1997 | DCP | 81m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Perfect Blue",
            "Fri, Sep 30, 2022 7:00 PM",
            "19:00",
            "30",
            "8",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/perfect-blue-1997.png.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "52A06841-6FB3-4403-9339-CC844BD168C5",
            "P",
            "Evening",
            "",
            "UCADF20221001",
            "Tsai Ming-Liang&nbsp;| 2018 | DCP | 94m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Light (光), Your Face (你的臉)",
            "Sat, Oct 1, 2022 6:00 PM",
            "18:00",
            "1",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/your-face-2018.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "66D6651B-3914-445C-B09E-A82A44A8D844",
            "P",
            "Evening",
            "",
            "UCADF20221002",
            "Jacques Rivette&nbsp;| 1966 | DCP | 140m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "The Nun",
            "Sun, Oct 2, 2022 5:00 PM",
            "17:00",
            "2",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/the-nun-1966.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "8DDA9F28-7A84-48CE-956C-0F01CF27172F",
            "P",
            "Evening",
            "",
            "UCADF20221003",
            "Frank Capra&nbsp;| 1934 | 35mm | 105m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "It Happened One Night",
            "Mon, Oct 3, 2022 7:00 PM",
            "19:00",
            "3",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/it-happened-one-night-1934.jpeg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "95469340-FBBC-4011-8AA5-DCAB07DC91B7",
            "P",
            "Evening",
            "",
            "UCADF20221004",
            "Wu Jing&nbsp;| 2017 | DCP | 123m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Wolf Warrior 2",
            "Tue, Oct 4, 2022 7:00 PM",
            "19:00",
            "4",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/wolf-warrior-2-2017.png",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "C00596E7-B8FA-4658-83F4-5A3600C6F1F9",
            "P",
            "Evening",
            "",
            "UCADF20221005",
            "Jackie Chan&nbsp;| 1988 | DCP | 122m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Police Story 2",
            "Wed, Oct 5, 2022 7:00 PM",
            "19:00",
            "5",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/police-story-2-1988.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "73BE440C-54B9-436A-97D0-6C1036D4DC32",
            "P",
            "Evening",
            "",
            "UCADF20221006",
            "Akira Kurosawa&nbsp;|&nbsp;1985 | DCP | 162m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Ran",
            "Thu, Oct 6, 2022 7:00 PM",
            "19:00",
            "6",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/ran-1985.png.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "CFF20EC0-25F6-46B3-8B42-F52A20ADFD09",
            "P",
            "Evening",
            "",
            "UCADF202210062",
            "Eiichi Yamamoto&nbsp;|&nbsp;1973 | DCP | 86m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Belladonna of Sadness",
            "Thu, Oct 6, 2022 7:00 PM",
            "19:00",
            "6",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/belladonna-of-sadness-1973.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "4EA3C317-F301-4826-B19A-57CDF927B0BC",
            "P",
            "Evening",
            "",
            "UCADF20221007",
            "Yeon Sang-ho |&nbsp;2016 | DCP | 118m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Train to Busan",
            "Fri, Oct 7, 2022 7:00 PM",
            "19:00",
            "7",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/train-to-busan-2016.jpeg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "515C10EC-7CC9-4554-8A3B-59868E211E6E",
            "P",
            "Evening",
            "",
            "UCADF20221008",
            "Baz Luhrmann |&nbsp;2022 | DCP | 159m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Elvis",
            "Sat, Oct 8, 2022 7:00 PM",
            "19:00",
            "8",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/elvis-2022.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "59407132-E70F-4B59-B0E9-5A28FFA0C836",
            "P",
            "Evening",
            "",
            "UCADF20221009",
            "Jacques Rivette |&nbsp;1974 | Digital | 193m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Céline and Julie Go Boating",
            "Sun, Oct 9, 2022 5:00 PM",
            "17:00",
            "9",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/celine-and-jullie-go-boating-1974.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "0FFB88FC-6962-4B4D-B01D-8CDE34FA2AB8",
            "P",
            "Evening",
            "",
            "UCADF20221010",
            "Howard Hawks |&nbsp;1938 | DCP | 102m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Bringing Up Baby",
            "Mon, Oct 10, 2022 7:00 PM",
            "19:00",
            "10",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/bringing-up-baby-1938.jpeg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "72F6250A-138A-4ABC-939C-C6311DEEC231",
            "P",
            "Evening",
            "",
            "UCADF20221011",
            "Lu Chuan |&nbsp;2009 | 35mm | 133m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "City of Life and Death",
            "Tue, Oct 11, 2022 7:00 PM",
            "19:00",
            "11",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/city-of-life-and-death-2009.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "6EE44AF5-C62A-4075-BAE9-D15C088A5D2F",
            "P",
            "Evening",
            "",
            "UCADF20221012",
            "Stanley Kwan |&nbsp;1991 | DCP | 126m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Center Stage",
            "Wed, Oct 12, 2022 7:00 PM",
            "19:00",
            "12",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/center-stage-1991.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "1C9FCA11-2F8E-4E05-AB8C-5A45F1CD3C8F",
            "P",
            "Evening",
            "",
            "UCADF202210132",
            "Marcell Jankovics |&nbsp;1981 | DCP | 90m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Son of the White Mare",
            "Thu, Oct 13, 2022 7:00 PM",
            "19:00",
            "13",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/son-of-the-white-mare-1981.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "6788F6F4-7667-40D2-9CCC-FC4DAF506F75",
            "P",
            "Evening",
            "",
            "UCADF20221013",
            "Gus Van Sant |&nbsp;1991 | DCP | 102m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "My Own Private Idaho",
            "Thu, Oct 13, 2022 7:00 PM",
            "19:00",
            "13",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/my-own-private-idaho-1999.jpeg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "47101944-0093-4031-80B6-7553B252F8D8",
            "P",
            "Evening",
            "",
            "UCADF20221014",
            "Ana Lily Amirpour |&nbsp;2014 | DCP | 101m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "A Girl Walks Home Alone at Night",
            "Fri, Oct 14, 2022 7:00 PM",
            "19:00",
            "14",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/a-girl-walks-home-alone-at-night-2014.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "B8086C1E-0B27-4494-B73F-F449FC84A6A2",
            "P",
            "Evening",
            "",
            "UCADF20221015",
            "Joseph Kosinski |&nbsp;2022 | DCP | 130m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Top Gun: Maverick",
            "Sat, Oct 15, 2022 7:00 PM",
            "19:00",
            "15",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/top-gun-maverick-2022.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ],
        [
            "1C42381A-4519-4DA4-BDC2-B927751C6561",
            "P",
            "Evening",
            "",
            "UCADF20221016",
            "Jacques Rivette |&nbsp;1976 | DCP | 121m<br />\n<br />\nTickets will be available for pick-up at the Doc Films ticketing stand in Ida Noyes 30 minutes before the start time of the respective screening.<br />\n<br />\nTicket Prices: $7",
            "Duelle",
            "Sun, Oct 16, 2022 5:00 PM",
            "17:00",
            "16",
            "9",
            "2022",
            "",
            "",
            "S",
            "E",
            "200",
            "Doc Films",
            "",
            "",
            "/content/Images/duelle-1976.jpg.jpg",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            [
                "1"
            ],
            [
                "1",
                "3",
                "4"
            ],
            "1212 E 59th St",
            "Chicago",
            "US-IL",
            "60637",
            "US",
            "",
            "",
            "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "Ida Noyes Hall",
            "UCArts",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "general admission",
            "Doc Films",
            "$7.00",
            "$7.00",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Public",
            "",
            "",
            ""
        ]
    ],
    "searchFilters": [
        {
            "name": "object_type_filter",
            "label": "Type Filter",
            "className": "objectTypeFilterList",
            "clearFilterLabel": "Clear Type Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "month_filter",
            "label": "Month Filter",
            "className": "monthFilterList",
            "clearFilterLabel": "Clear Month Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "city_filter",
            "label": "City Filter",
            "className": "cityFilterList",
            "clearFilterLabel": "Clear City Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "venue_filter",
            "label": "Venue Filter",
            "className": "venueFilterList",
            "clearFilterLabel": "Clear Venue Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "category_filter",
            "label": "Category Filter",
            "className": "categoryFilterList",
            "clearFilterLabel": "Clear Category Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "organization_short_description_filter",
            "label": "Organization Filter",
            "className": "organizationShortDescriptionFilterList",
            "clearFilterLabel": "Clear Organization Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "filter1",
            "label": "Filter 1",
            "className": "customFilterList",
            "clearFilterLabel": "Clear Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "filter2",
            "label": "Filter 2",
            "className": "customFilterList",
            "clearFilterLabel": "Clear Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "filter3",
            "label": "Filter 3",
            "className": "customFilterList",
            "clearFilterLabel": "Clear Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "filter4",
            "label": "Filter 4",
            "className": "customFilterList",
            "clearFilterLabel": "Clear Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "filter_parent1",
            "label": "Filter Parent 1",
            "className": "customFilterParentList",
            "clearFilterLabel": "Clear Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "filter_parent2",
            "label": "Filter Parent 2",
            "className": "customFilterParentList",
            "clearFilterLabel": "Clear Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "multifilter1",
            "label": "Multi Filter 1",
            "className": "customFilterList",
            "clearFilterLabel": "Clear Filter",
            "selectedValue": "",
            "values": []
        },
        {
            "name": "multifilter2",
            "label": "Multi Filter 2",
            "className": "customFilterList",
            "clearFilterLabel": "Clear Filter",
            "selectedValue": "",
            "values": []
        }
    ],
    "searchCalendarFilters": [
        {
            "name": "calendar_days",
            "label": "Calendar Days",
            "className": "dayFilterList",
            "clearFilterLabel": "Clear Day Filter",
            "selectedValue": "",
            "values": [
                [
                    "2022-09-27T00:00:00.000",
                    "1"
                ],
                [
                    "2022-09-30T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-01T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-02T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-03T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-04T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-05T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-07T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-08T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-09T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-10T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-11T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-12T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-14T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-15T00:00:00.000",
                    "1"
                ],
                [
                    "2022-10-16T00:00:00.000",
                    "1"
                ],
                [
                    "2022-09-28T00:00:00.000",
                    "2"
                ],
                [
                    "2022-09-29T00:00:00.000",
                    "2"
                ],
                [
                    "2022-10-06T00:00:00.000",
                    "2"
                ],
                [
                    "2022-10-13T00:00:00.000",
                    "2"
                ]
            ]
        }
    ],
    "searchLabels": {
        "performances": "Events",
        "date": "Date",
        "unavailable_message": "Not Available",
        "sold_out_message": "Sold Out!",
        "on_sale_message": "On sale",
        "to_be_determined_message": "TBD",
        "next": "»",
        "previous": "«",
        "next_month": "Next month",
        "previous_month": "Previous month",
        "avail_excellent": "Excellent",
        "avail_good": "Good",
        "avail_limited": "Limited",
        "avail_sold_out": "Sold Out",
        "no_results_message": "We're sorry, there are no events matching your search.",
        "promo_item": "This item is available with a promocode",
        "buy_seats_message": "Tickets",
        "buy_bundle_message": "Buy",
        "buy_item_message": "Buy",
        "pageNext": "Next",
        "pagePrev": "Previous",
        "buy_gift_message": "Donate",
        "buy_storedvalueitem_message": "Buy",
        "upsell_seats_message": "Upgrade",
        "upsell_bundle_message": "Upgrade",
        "upsell_item_message": "Upgrade",
        "upsell_gift_message": "Upgrade",
        "upsell_storedvalueitem_message": "Upgrade",
        "upsell_popup_title": "Interested in Upgrading?",
        "addon_seats_message": "Select",
        "addon_bundle_message": "Select",
        "addon_item_message": "Select",
        "addon_gift_message": "Select",
        "addon_storedvalueitem_message": "Select",
        "exchange_seats_message": "Select",
        "exchange_bundle_message": "Select",
        "exchange_item_message": "Select",
        "exchange_gift_message": "Select",
        "exchange_storedvalueitem_message": "Select",
        "describe_seats_message": "%action, %name, %datetime",
        "describe_bundle_message": "%action, %name",
        "describe_item_message": "%action, %name",
        "describe_gift_message": "%action, %name",
        "describe_storedvalueitem_message": "%action, %name",
        "describe_article_message": "%action, %name",
        "see_events_for_date": "See events for %m %d",
        "select_your_time": "Please select your time",
        "view_article_message": "View",
        "price_title": "Price",
        "pagination": "Pagination",
        "availability_title": "Availability",
        "active_promo_codes": "Active promotions:",
        "promo_code_item_title": "This item is available with a promocode",
        "has_promo_code": "false",
        "brand_path": "../../content/images/branding/"
    },
    "searchSUMO": {
        "availability_access": "true",
        "mapSelect_access": "true"
    },
    "pagination": {
        "current_page": "1",
        "page_size": "80",
        "total_pages": "1"
    },
    "loginLabels": {
        "pageTarget": "maintainAccount.asp",
        "loginBoxClass": "login-required",
        "forgotPassword": "true",
        "formLoginName": "",
        "accountLogin": "true"
    },
    "contextId": "",
    "articleId": "F5602A6B-6B4D-4AC2-A9CF-9B1A03B4BDBA",
    "articleSearchId": "",
    "salesType": "P",
    "sToken": "1,e6aa544d,63237e7e,39DF7F5E-E270-4AA9-8E2B-849474C657EC,rWbhlwomYohRW7GofHxC1kDlhQM="
}


parent_directory = r"C:\Users\camer\docfilms-github\site\public\calendar"
output_name = r"2022_fall_ticketing_links.txt"
f = open(os.path.join(parent_directory, output_name), 'w', encoding='utf-8')

for item in ticketing_dict["searchResults"]:
    f.write(item[6] + r': https://tickets.uchicago.edu/Online/seatSelect.asp?createBO::WSmap=1&BOparam::WSmap::loadBestAvailable::performance_ids=' + item[0] + "\n\n")

f.close()