import os

# instructions for using this script to get links to ticketing events:

# open chrome, go to the page for Doc Films' season on the Logan Box Office ticketing page
# open inspect element
# go to the console tab
# enter `copy(articleContext)` -- this copies the variable with all the data from the Logan event database to your clipboard
# paste it into the `ticketing_dict` variable in this script
# edit your `parent_directory` and `output_name` variables if need be (way down at the bottom)
# run the script and you're done!

def main():

    # the file path to the ticketing_links/ directory on your local machine
    parent_directory = r"/Users/selalipotakey/docfilms-git/site/database/ticketing_links"

    # the file name of the text file you want the links written out to
    # follow the format YYYY_quarter_ticketing_links.txt
    output_name = r"2023_fall_ticketing_links.txt"

    # outputs a .txt file with just the URLs
    simple_links = True

    # outputs a .txt file with the URLs formatted into an <a href=""></a> attribute in HTML (for easy copy-pasting into the webpages)
    website_hrefs = True

    if simple_links:
        f = open(os.path.join(parent_directory, output_name), 'w', encoding='utf-8')

        for item in ticketing_dict["searchResults"]:
            f.write(item[6] + ':\n' + r'https://tickets.uchicago.edu/Online/seatSelect.asp?createBO::WSmap=1&BOparam::WSmap::loadBestAvailable::performance_ids=' + item[0] + "\n\n")

        f.close()
    
    if website_hrefs:
        modified_output_name = 'hrefs_' + output_name 
        f = open(os.path.join(parent_directory, modified_output_name), 'w', encoding='utf-8')

        for item in ticketing_dict["searchResults"]:
            link = r'https://tickets.uchicago.edu/Online/seatSelect.asp?createBO::WSmap=1&BOparam::WSmap::loadBestAvailable::performance_ids=' + item[0]

            href = r'<p><b>Tickets can be bought <u><a href="' + link + r'" target="_blank">here</a></u>.</b></p>'

            f.write(item[6] + ':\n' + href + "\n\n")

        f.close()


ticketing_dict = {
  "searchHeaders": [
    "Id",
    "Object Type",
    "Type",
    "Category",
    "Name",
    "Description",
    "Short Description",
    "Start Date",
    "Start Date time",
    "Start Date date",
    "Start Date month",
    "Start Date year",
    "End Date",
    "On Sale Date",
    "Sales Status",
    "Availability",
    "Available Number",
    "Keywords",
    "Additional Info",
    "Group",
    "Image 1",
    "Image 2",
    "image1_alt_text",
    "image2_alt_text",
    "thumbnail",
    "Data 1",
    "Data 2",
    "Data 3",
    "Data 4",
    "Data 5",
    "Data 6",
    "Data 7",
    "Data 8",
    "Data 9",
    "Data 10",
    "Data 11",
    "Data 12",
    "Data 13",
    "Data 14",
    "Data 15",
    "Data 16",
    "filter1",
    "filter2",
    "filter3",
    "filter4",
    "filter_parent1",
    "filter_child2",
    "filter_parent2",
    "filter_child1",
    "multifilter1",
    "multifilter2",
    "Organization Short Description",
    "Sales Type",
    "Options",
    "Street",
    "City",
    "Province / State",
    "Postal Code",
    "Country",
    "Longitude",
    "Latitude",
    "Venue ID",
    "Venue Name",
    "Venue Description",
    "Venue Short Description",
    "Venue Group",
    "Venue Data 1",
    "Venue Data 2",
    "Venue Data 3",
    "Venue Data 4",
    "Venue Data 5",
    "Venue Data 6",
    "Venue Data 7",
    "Venue Data 8",
    "Venue Data 9",
    "Venue Data 10",
    "Venue Data 11",
    "Venue Data 12",
    "Venue Type",
    "Series Name",
    "Minimum Price",
    "Maximum Price",
    "Upsell Article",
    "Add-on Article",
    "email",
    "e_address1",
    "e_address2",
    "e_address3",
    "customer_id",
    "tracking_code",
    "twitter_search_term",
    "external_reference_code",
    "access",
    "Venue Organization Id",
    "Meta Description",
    ""
  ],
  "searchNames": [
    "id",
    "object_type",
    "type",
    "category",
    "name",
    "description",
    "short_description",
    "start_date",
    "start_date_time",
    "start_date_date",
    "start_date_month",
    "start_date_year",
    "end_date",
    "on_sale_date",
    "sales_status",
    "availability_status",
    "availability_num",
    "keywords",
    "additional_info",
    "group",
    "image1",
    "image2",
    "image1_alt_text",
    "image2_alt_text",
    "thumbnail",
    "data1",
    "data2",
    "data3",
    "data4",
    "data5",
    "data6",
    "data7",
    "data8",
    "data9",
    "data10",
    "data11",
    "data12",
    "data13",
    "data14",
    "data15",
    "data16",
    "filter1",
    "filter2",
    "filter3",
    "filter4",
    "filter_parent1",
    "filter_child2",
    "filter_parent2",
    "filter_child1",
    "multifilter1",
    "multifilter2",
    "organization_short_description",
    "sales_type",
    "options",
    "street",
    "city",
    "state",
    "zip",
    "country",
    "longitude",
    "latitude",
    "venue_id",
    "venue_name",
    "venue_description",
    "venue_short_description",
    "venue_group",
    "venue_data1",
    "venue_data2",
    "venue_data3",
    "venue_data4",
    "venue_data5",
    "venue_data6",
    "venue_data7",
    "venue_data8",
    "venue_data9",
    "venue_data10",
    "venue_data11",
    "venue_data12",
    "venue_type",
    "series_name",
    "min_price",
    "max_price",
    "upsell_article_id",
    "addon_article_id",
    "email",
    "e_address1",
    "e_address2",
    "e_address3",
    "customer_id",
    "tracking_code",
    "twitter_search_term",
    "external_reference_code",
    "access",
    "organization_id",
    "meta_description",
    ""
  ],
  "searchResults": [
    [
      "AEF55645-A767-428E-BDCA-CF087C67F22A",
      "M",
      "Merchandise",
      "Doc Films",
      "Doc Quarter Pass Fall 2023",
      "This season pass allows entry into all general admission screenings during the quarter. Please visit the Doc Films website to see quarter pass admission policies for special events. If you have bought a quarter pass in the previous quarter, or purchased a single ticket in the first two weeks of the quarter, please purchase your pass in person and not online.&nbsp;",
      "Doc Quarter Pass Fall 2023",
      "Wed, Sep 20, 2023 12:00 AM",
      "00:00",
      "20",
      "8",
      "2023",
      "Sun, Dec 3, 2023 12:00 AM",
      "",
      "S",
      "",
      "",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/docfall23pass.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [],
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "$40.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    [
      "E5D37239-C269-4DD9-A03A-A5EEB46028E5",
      "P",
      "Evening",
      "",
      "DOC20231012",
      "Danny Boyle | 1996 | 93m | DCP",
      "Trainspotting",
      "Thu, Oct 12, 2023 7:00 PM",
      "19:00",
      "12",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Trainspotting.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "412931CD-2443-4542-BC05-600A3E3B9827",
      "P",
      "Evening",
      "",
      "DOC20231012E",
      "Frank Henenlotter | 1982 | 91m | DCP",
      "Basket Case",
      "Thu, Oct 12, 2023 9:30 PM",
      "21:30",
      "12",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Basket-Case.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "E5277679-5B4C-4282-BE71-A668EF3D5C05",
      "P",
      "Evening",
      "",
      "DOC20231013",
      "John Cassavetes | 1974 | 155m | DCP",
      "A Woman Under the Influence",
      "Fri, Oct 13, 2023 7:00 PM",
      "19:00",
      "13",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/woman-under-the-influence.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "E01A60FA-ABB4-469D-A3E7-06AD1090278D",
      "P",
      "Matinee",
      "",
      "DOC20231014M",
      "<p>John Cassavetes | 1974 | 155m | DCP</p>",
      "A Woman Under the Influence",
      "Sat, Oct 14, 2023 4:00 PM",
      "16:00",
      "14",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "197",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/woman-under-the-influence.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "0AFB1C65-9169-4DDD-B11A-9A795C0CCC99",
      "P",
      "Evening",
      "",
      "DOC20231014",
      "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson | 2023 | 140m | DCP",
      "Spider-man: Across the Spider-verse",
      "Sat, Oct 14, 2023 7:00 PM",
      "19:00",
      "14",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "192",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Spider-Man.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "979E377D-D5C0-4D0E-ABC2-C82E224AA848",
      "P",
      "Evening",
      "",
      "DOC20231015",
      "Danny Boyle | 1996 | 136m | DCP",
      "Trainspotting",
      "Sun, Oct 15, 2023 4:30 PM",
      "16:30",
      "15",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "197",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Trainspotting.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "B1906156-BC83-4D11-AFF4-1158A4E63112",
      "P",
      "Evening",
      "",
      "DOC20231016",
      "Marcel Carné | 1939 | 93m | DCP",
      "Le jour se lève",
      "Mon, Oct 16, 2023 7:00 PM",
      "19:00",
      "16",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Le-jour-se-le-cve.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "954335C2-CC80-41D5-ADFA-97B41D72DEE9",
      "P",
      "Evening",
      "",
      "DOC20231017",
      "Oscar Micheaux | 1925 | 102m | DCP",
      "Body and Soul",
      "Tue, Oct 17, 2023 7:00 PM",
      "19:00",
      "17",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Body-and-Soul.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "24C1E36E-EF4B-43E6-AE94-FC7ADE0469AC",
      "P",
      "Evening",
      "",
      "DOC20231018",
      "Ang Lee | 2012 | 127m | DCP",
      "Life of Pi",
      "Wed, Oct 18, 2023 7:00 PM",
      "19:00",
      "18",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Life-of-Pi.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "D235680B-A92B-407E-8A3F-94924EC08C1D",
      "P",
      "Evening",
      "",
      "DOC20231019",
      "François Ozon | 2003 | 103m | 35mm",
      "Swimming Pool",
      "Thu, Oct 19, 2023 7:00 PM",
      "19:00",
      "19",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/swimming-pools-2003.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "3B4964B6-2FAD-4028-916D-0A67663C366B",
      "P",
      "Evening",
      "",
      "DOC20231019E",
      "Joseph W. Sarno | 1966 | 80m | DCP",
      "Red Roses of Passion",
      "Thu, Oct 19, 2023 9:30 PM",
      "21:30",
      "19",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Red-Roses-of-Passion.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "3B4D03F5-AEA0-4D74-A875-ED53A26A299F",
      "P",
      "Evening",
      "",
      "DOC20231020",
      "Terrence Malick | 1973 | 93m | DCP",
      "Badlands",
      "Fri, Oct 20, 2023 7:00 PM",
      "19:00",
      "20",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/badlands.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "76229C7E-71C6-4440-A4F1-324E85C5CC0F",
      "P",
      "Matinee",
      "",
      "DOC20231021M",
      "<p>James Mangold | 2023 | 154m | DCP</p>",
      "Indiana Jones and the Dial of Destiny",
      "Sat, Oct 21, 2023 2:00 PM",
      "14:00",
      "21",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "199",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Indiana-Jones.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "C522062D-81A4-4BAF-9053-7EDA0CAC9B70",
      "P",
      "Matinee",
      "",
      "DOC20231022",
      "Terrence Malick | 1973 | 93m | DCP",
      "Badlands",
      "Sun, Oct 22, 2023 3:00 PM",
      "15:00",
      "22",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/badlands.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "CDC099D2-EE9A-4D7C-911B-6BDB70402279",
      "P",
      "Evening",
      "",
      "DOC20231023",
      "Mervyn LeRoy | 1932 | 92m |&nbsp;35mm",
      "I Am a Fugitive From a Chain Gang",
      "Mon, Oct 23, 2023 7:00 PM",
      "19:00",
      "23",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Fugitive-from-a-Chain-Gang.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "A6FA7653-3CB7-4A11-A375-EF4E86D66714",
      "P",
      "Evening",
      "",
      "DOC20231024",
      "Howard Smith and Sarah Kernochan | 1972 | 88m | Digital",
      "Marjoe",
      "Tue, Oct 24, 2023 7:00 PM",
      "19:00",
      "24",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Marjoe.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "74CBB65B-6CBB-4CCF-87DE-AB961CC30770",
      "P",
      "Evening",
      "",
      "DOC20231025M",
      "Dave Steck | 2024&nbsp; | Approximately 42min | DCP",
      "Catalyst",
      "Wed, Oct 25, 2023 4:00 PM",
      "16:00",
      "25",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Duro2_still.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "00FE2409-114E-4771-8D86-168821B37588",
      "P",
      "Evening",
      "",
      "DOC20231025",
      "Ang Lee | 1997 | 113m | 35mm",
      "The Ice Storm",
      "Wed, Oct 25, 2023 7:00 PM",
      "19:00",
      "25",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "198",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Ice-Storm.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "329D6497-32FA-4425-8500-406CCCE090CD",
      "P",
      "Evening",
      "",
      "DOC20231026",
      "Gaspar Noé | 2002 | 97m | DCP",
      "Irréversible",
      "Thu, Oct 26, 2023 7:00 PM",
      "19:00",
      "26",
      "9",
      "2023",
      "",
      "",
      "S",
      "E",
      "200",
      "Doc Fall 2023",
      "",
      "",
      "/content/Images/UC-Arts-Images/Doc_Fall23/Irreversible.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "3466AB34-D1B0-4CA1-A71E-43A05593BC0B",
      "Max Palevsky Cinema",
      "Max Palevsky Cinema at Ida Noyes Hall",
      "Max Palevsky Cinema",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc 2023-2024",
      "$7.00",
      "$7.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ]
  ],
  "searchFilters": [
    {
      "name": "object_type_filter",
      "label": "Type Filter",
      "className": "objectTypeFilterList",
      "clearFilterLabel": "Clear Type Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "month_filter",
      "label": "Month Filter",
      "className": "monthFilterList",
      "clearFilterLabel": "Clear Month Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "city_filter",
      "label": "City Filter",
      "className": "cityFilterList",
      "clearFilterLabel": "Clear City Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "venue_filter",
      "label": "Venue Filter",
      "className": "venueFilterList",
      "clearFilterLabel": "Clear Venue Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "category_filter",
      "label": "Category Filter",
      "className": "categoryFilterList",
      "clearFilterLabel": "Clear Category Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "organization_short_description_filter",
      "label": "Organization Filter",
      "className": "organizationShortDescriptionFilterList",
      "clearFilterLabel": "Clear Organization Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter1",
      "label": "Filter 1",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter2",
      "label": "Filter 2",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter3",
      "label": "Filter 3",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter4",
      "label": "Filter 4",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter_parent1",
      "label": "Filter Parent 1",
      "className": "customFilterParentList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter_parent2",
      "label": "Filter Parent 2",
      "className": "customFilterParentList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "multifilter1",
      "label": "Multi Filter 1",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "multifilter2",
      "label": "Multi Filter 2",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    }
  ],
  "searchCalendarFilters": [
    {
      "name": "calendar_days",
      "label": "Calendar Days",
      "className": "dayFilterList",
      "clearFilterLabel": "Clear Day Filter",
      "selectedValue": "",
      "values": [
        [
          "2023-09-20T00:00:00.000",
          "1"
        ],
        [
          "2023-11-28T00:00:00.000",
          "1"
        ],
        [
          "2023-10-13T00:00:00.000",
          "1"
        ],
        [
          "2023-11-17T00:00:00.000",
          "1"
        ],
        [
          "2023-10-15T00:00:00.000",
          "1"
        ],
        [
          "2023-10-16T00:00:00.000",
          "1"
        ],
        [
          "2023-10-17T00:00:00.000",
          "1"
        ],
        [
          "2023-10-18T00:00:00.000",
          "1"
        ],
        [
          "2023-11-19T00:00:00.000",
          "1"
        ],
        [
          "2023-10-20T00:00:00.000",
          "1"
        ],
        [
          "2023-10-21T00:00:00.000",
          "1"
        ],
        [
          "2023-10-22T00:00:00.000",
          "1"
        ],
        [
          "2023-10-23T00:00:00.000",
          "1"
        ],
        [
          "2023-10-24T00:00:00.000",
          "1"
        ],
        [
          "2023-11-27T00:00:00.000",
          "1"
        ],
        [
          "2023-12-03T00:00:00.000",
          "1"
        ],
        [
          "2023-10-27T00:00:00.000",
          "1"
        ],
        [
          "2023-11-29T00:00:00.000",
          "1"
        ],
        [
          "2023-10-29T00:00:00.000",
          "1"
        ],
        [
          "2023-10-30T00:00:00.000",
          "1"
        ],
        [
          "2023-10-31T00:00:00.000",
          "1"
        ],
        [
          "2023-11-01T00:00:00.000",
          "1"
        ],
        [
          "2023-12-01T00:00:00.000",
          "1"
        ],
        [
          "2023-11-03T00:00:00.000",
          "1"
        ],
        [
          "2023-11-06T00:00:00.000",
          "1"
        ],
        [
          "2023-11-07T00:00:00.000",
          "1"
        ],
        [
          "2023-11-08T00:00:00.000",
          "1"
        ],
        [
          "2023-11-10T00:00:00.000",
          "1"
        ],
        [
          "2023-11-11T00:00:00.000",
          "1"
        ],
        [
          "2023-11-12T00:00:00.000",
          "1"
        ],
        [
          "2023-11-13T00:00:00.000",
          "1"
        ],
        [
          "2023-11-14T00:00:00.000",
          "1"
        ],
        [
          "2023-11-15T00:00:00.000",
          "1"
        ],
        [
          "2023-10-12T00:00:00.000",
          "2"
        ],
        [
          "2023-10-14T00:00:00.000",
          "2"
        ],
        [
          "2023-10-19T00:00:00.000",
          "2"
        ],
        [
          "2023-10-25T00:00:00.000",
          "2"
        ],
        [
          "2023-10-26T00:00:00.000",
          "2"
        ],
        [
          "2023-10-28T00:00:00.000",
          "2"
        ],
        [
          "2023-11-02T00:00:00.000",
          "2"
        ],
        [
          "2023-11-18T00:00:00.000",
          "2"
        ],
        [
          "2023-11-04T00:00:00.000",
          "2"
        ],
        [
          "2023-11-30T00:00:00.000",
          "2"
        ],
        [
          "2023-11-09T00:00:00.000",
          "2"
        ],
        [
          "2023-12-02T00:00:00.000",
          "2"
        ],
        [
          "2023-11-16T00:00:00.000",
          "2"
        ]
      ]
    }
  ],
  "performanceDays": [
    {
      "name": "performance_days",
      "label": "Performance Days",
      "className": "dayFilterList",
      "clearFilterLabel": "Clear Day Filter",
      "selectedValue": "",
      "values": []
    }
  ],
  "searchLabels": {
    "performances": "Events",
    "date": "Date",
    "unavailable_message": "Not Available",
    "sold_out_message": "Sold Out!",
    "on_sale_message": "On sale",
    "to_be_determined_message": "TBD",
    "next": "»",
    "previous": "«",
    "next_month": "Next month",
    "previous_month": "Previous month",
    "avail_excellent": "Excellent",
    "avail_good": "Good",
    "avail_limited": "Limited",
    "avail_sold_out": "Sold Out",
    "no_results_message": "We're sorry, there are no events matching your search.",
    "promo_item": "This item is available with a promocode",
    "buy_seats_message": "Tickets",
    "buy_bundle_message": "Buy",
    "buy_item_message": "Buy",
    "pageNext": "Next",
    "pagePrev": "Previous",
    "buy_gift_message": "Donate",
    "buy_storedvalueitem_message": "Buy",
    "upsell_seats_message": "Upgrade",
    "upsell_bundle_message": "Upgrade",
    "upsell_item_message": "Upgrade",
    "upsell_gift_message": "Upgrade",
    "upsell_storedvalueitem_message": "Upgrade",
    "upsell_popup_title": "Interested in Upgrading?",
    "addon_seats_message": "Select",
    "addon_bundle_message": "Select",
    "addon_item_message": "Select",
    "addon_gift_message": "Select",
    "addon_storedvalueitem_message": "Select",
    "exchange_seats_message": "Select",
    "exchange_bundle_message": "Select",
    "exchange_item_message": "Select",
    "exchange_gift_message": "Select",
    "exchange_storedvalueitem_message": "Select",
    "describe_seats_message": "%action, %name, %datetime",
    "describe_bundle_message": "%action, %name",
    "describe_item_message": "%action, %name",
    "describe_gift_message": "%action, %name",
    "describe_storedvalueitem_message": "%action, %name",
    "describe_article_message": "%action, %name",
    "see_events_for_date": "See events for %m %d",
    "select_your_time": "Please select your time",
    "view_article_message": "View",
    "price_title": "Price",
    "pagination": "Pagination",
    "availability_title": "Availability",
    "active_promo_codes": "Active promotions:",
    "promo_code_item_title": "This item is available with a promocode",
    "has_promo_code": "false",
    "brand_path": "../../content/images/branding/"
  },
  "searchSUMO": {
    "availability_access": "true",
    "mapSelect_access": "true"
  },
  "pagination": {
    "current_page": "1",
    "page_size": "20",
    "total_pages": "3"
  },
  "loginLabels": {
    "pageTarget": "maintainAccount.asp",
    "loginBoxClass": "login-required",
    "forgotPassword": "true",
    "formLoginName": "",
    "accountLogin": "true"
  },
  "contextId": "",
  "articleId": "2BDF68C9-C949-4F28-BB27-4D0B2B829ADC",
  "articleSearchId": "",
  "salesType": "P",
  "sToken": "1,d9e8936d,65277869,6B2DAC25-79D7-4BDA-9A4D-4A1C07CFEBAD,/Lm+ajHln2WIxvxvRhqKdR4fWQ4="
}


if __name__ == '__main__':
    main()

