import os

# instructions for using this script to get links to ticketing events:

# open chrome, go to the page for Doc Films' season on the Logan Box Office ticketing page
# open inspect element
# go to the console tab
# enter `copy(articleContext)` -- this copies the variable with all the data from the Logan event database to your clipboard
# paste it into the `ticketing_dict` variable in this script
# edit your `parent_directory` and `output_name` variables if need be (way down at the bottom)
# run the script and you're done!

def main():

    # the file path to the ticketing_links/ directory on your local machine
    parent_directory = r"/Users/selalipotakey/docfilms-git/site/database/ticketing_ids.py"

    # the file name of the text file you want the links written out to
    # follow the format YYYY_quarter_ticketing_links.txt
    output_name = r"2023_summer_ticketing_links.txt"

    # outputs a .txt file with just the URLs
    simple_links = True

    # outputs a .txt file with the URLs formatted into an <a href=""></a> attribute in HTML (for easy copy-pasting into the webpages)
    website_hrefs = True

    if simple_links:
        f = open(os.path.join(parent_directory, output_name), 'w', encoding='utf-8')

        for item in ticketing_dict["searchResults"]:
            f.write(item[6] + ':\n' + r'https://tickets.uchicago.edu/Online/seatSelect.asp?createBO::WSmap=1&BOparam::WSmap::loadBestAvailable::performance_ids=' + item[0] + "\n\n")

        f.close()
    
    if website_hrefs:
        modified_output_name = 'hrefs_' + output_name 
        f = open(os.path.join(parent_directory, modified_output_name), 'w', encoding='utf-8')

        for item in ticketing_dict["searchResults"]:
            link = r'https://tickets.uchicago.edu/Online/seatSelect.asp?createBO::WSmap=1&BOparam::WSmap::loadBestAvailable::performance_ids=' + item[0]

            href = r'<p><b>Tickets can be bought <u><a href="' + link + r'" target="_blank">here</a></u>.</b></p>'

            f.write(item[6] + ':\n' + href + "\n\n")

        f.close()


ticketing_dict = {
  "searchHeaders": [
    "Id",
    "Object Type",
    "Type",
    "Category",
    "Name",
    "Description",
    "Short Description",
    "Start Date",
    "Start Date time",
    "Start Date date",
    "Start Date month",
    "Start Date year",
    "End Date",
    "On Sale Date",
    "Sales Status",
    "Availability",
    "Available Number",
    "Keywords",
    "Additional Info",
    "Group",
    "Image 1",
    "Image 2",
    "thumbnail",
    "Data 1",
    "Data 2",
    "Data 3",
    "Data 4",
    "Data 5",
    "Data 6",
    "Data 7",
    "Data 8",
    "Data 9",
    "Data 10",
    "Data 11",
    "Data 12",
    "Data 13",
    "Data 14",
    "Data 15",
    "Data 16",
    "filter1",
    "filter2",
    "filter3",
    "filter4",
    "filter_parent1",
    "filter_child2",
    "filter_parent2",
    "filter_child1",
    "multifilter1",
    "multifilter2",
    "Organization Short Description",
    "Sales Type",
    "Options",
    "Street",
    "City",
    "Province / State",
    "Postal Code",
    "Country",
    "Longitude",
    "Latitude",
    "Venue ID",
    "Venue Name",
    "Venue Description",
    "Venue Short Description",
    "Venue Group",
    "Venue Data 1",
    "Venue Data 2",
    "Venue Data 3",
    "Venue Data 4",
    "Venue Data 5",
    "Venue Data 6",
    "Venue Data 7",
    "Venue Data 8",
    "Venue Data 9",
    "Venue Data 10",
    "Venue Data 11",
    "Venue Data 12",
    "Venue Type",
    "Series Name",
    "Minimum Price",
    "Maximum Price",
    "Upsell Article",
    "Add-on Article",
    "email",
    "e_address1",
    "e_address2",
    "e_address3",
    "customer_id",
    "tracking_code",
    "twitter_search_term",
    "external_reference_code",
    "access",
    "Venue Organization Id",
    "Meta Description",
    ""
  ],
  "searchNames": [
    "id",
    "object_type",
    "type",
    "category",
    "name",
    "description",
    "short_description",
    "start_date",
    "start_date_time",
    "start_date_date",
    "start_date_month",
    "start_date_year",
    "end_date",
    "on_sale_date",
    "sales_status",
    "availability_status",
    "availability_num",
    "keywords",
    "additional_info",
    "group",
    "image1",
    "image2",
    "thumbnail",
    "data1",
    "data2",
    "data3",
    "data4",
    "data5",
    "data6",
    "data7",
    "data8",
    "data9",
    "data10",
    "data11",
    "data12",
    "data13",
    "data14",
    "data15",
    "data16",
    "filter1",
    "filter2",
    "filter3",
    "filter4",
    "filter_parent1",
    "filter_child2",
    "filter_parent2",
    "filter_child1",
    "multifilter1",
    "multifilter2",
    "organization_short_description",
    "sales_type",
    "options",
    "street",
    "city",
    "state",
    "zip",
    "country",
    "longitude",
    "latitude",
    "venue_id",
    "venue_name",
    "venue_description",
    "venue_short_description",
    "venue_group",
    "venue_data1",
    "venue_data2",
    "venue_data3",
    "venue_data4",
    "venue_data5",
    "venue_data6",
    "venue_data7",
    "venue_data8",
    "venue_data9",
    "venue_data10",
    "venue_data11",
    "venue_data12",
    "venue_type",
    "series_name",
    "min_price",
    "max_price",
    "upsell_article_id",
    "addon_article_id",
    "email",
    "e_address1",
    "e_address2",
    "e_address3",
    "customer_id",
    "tracking_code",
    "twitter_search_term",
    "external_reference_code",
    "access",
    "organization_id",
    "meta_description",
    ""
  ],
  "searchResults": [
    [
      "4A3B9393-7E29-4609-A20F-AE81FD8C827A",
      "M",
      "Merchandise",
      "Doc Films",
      "UCArts-Doc Films Quarter Pass Summer 2023",
      "This season pass allows entry into all general admission screenings during the quarter. Please visit the Doc Films website to see quarter pass admission policies for special events. If you have bought a quarter pass in the previous quarter, or purchased a single ticket in the first two weeks of the quarter, please purchase your pass in person and not online.&nbsp;",
      "Doc Films Quarter Pass Summer 2023",
      "Fri, Jun 9, 2023 12:00 AM",
      "00:00",
      "9",
      "5",
      "2023",
      "Sun, Aug 13, 2023 12:00 AM",
      "",
      "S",
      "",
      "",
      "Doc Films",
      "",
      "",
      "/content/Images/summer-pass_page-0001-3.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [],
      [],
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "$25.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    [
      "D2BE94AF-D253-4DC1-9659-5DA1DF6B56F4",
      "P",
      "Evening",
      "",
      "DOC20230623M",
      "Paul Mazursky | 1969 | 35mm | 105m",
      "Bob & Carol & Ted & Alice",
      "Fri, Jun 23, 2023 6:00 PM",
      "18:00",
      "23",
      "5",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "https://tickets.uchicago.edu/Online/default.asp?doWork::WScontent::loadArticle=Load&BOparam::WScontent::loadArticle::article_id=5B46B67B-FA8D-4216-AAAE-5EF756228310&BOparam::WScontent::loadArticle::context_id=D2BE94AF-D253-4DC1-9659-5DA1DF6B56F4",
      "",
      "/content/Images/bob-carol-ted-alice-1969.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "02C5AA50-9084-4D90-AE41-99CCD1910AEB",
      "P",
      "Evening",
      "",
      "DOC20230623E",
      "Robert Altman | 1973 | Digital | 112m",
      "The Long Goodbye",
      "Fri, Jun 23, 2023 8:30 PM",
      "20:30",
      "23",
      "5",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "https://tickets.uchicago.edu/Online/default.asp?doWork::WScontent::loadArticle=Load&BOparam::WScontent::loadArticle::article_id=5B46B67B-FA8D-4216-AAAE-5EF756228310&BOparam::WScontent::loadArticle::context_id=02C5AA50-9084-4D90-AE41-99CCD1910AEB",
      "",
      "/content/Images/the-long-goodbye-1973.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "1F73AA9C-BB39-42C8-8A1F-25A9E678C9EC",
      "P",
      "Evening",
      "",
      "DOC20230624M",
      "Robert Altman | 1973 | Digital | 112m",
      "The Long Goodbye",
      "Sat, Jun 24, 2023 6:00 PM",
      "18:00",
      "24",
      "5",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/the-long-goodbye-1973.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "806A6E51-820A-4242-A0D5-A1595AC3446B",
      "P",
      "Evening",
      "",
      "DOC20230624E",
      "Paul Mazursky | 1969 | 35mm | 105m",
      "Bob & Carol & Ted & Alice",
      "Sat, Jun 24, 2023 8:30 PM",
      "20:30",
      "24",
      "5",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/bob-carol-ted-alice-1969.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "87815B79-7B50-4FD8-A6E3-68D37D1B847E",
      "P",
      "Evening",
      "",
      "DOC20230629",
      "Albert Serra | 2022 | DCP | 162m",
      "Pacifiction",
      "Thu, Jun 29, 2023 7:00 PM",
      "19:00",
      "29",
      "5",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/pacifiction-2022.png",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "FDE9F1F3-7CFA-4D23-9851-B05DED1A9F98",
      "P",
      "Evening",
      "",
      "DOC20230630M",
      "Robert Altman | 1975 | DCP | 160m",
      "Nashville",
      "Fri, Jun 30, 2023 4:00 PM",
      "16:00",
      "30",
      "5",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/nashville-1975.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "8844C315-6CAC-412C-BFED-E28B63B8F2D9",
      "P",
      "Evening",
      "",
      "DOC20230630E",
      "Michael Schultz | 1976 | 35mm | 97m",
      "Car Wash",
      "Fri, Jun 30, 2023 7:00 PM",
      "19:00",
      "30",
      "5",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/car-wash-1976.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "7D7F31FE-6E57-4F8D-91B6-59AB90010A9F",
      "P",
      "Evening",
      "",
      "DOC20230701M",
      "Michael Schultz | 1976 | 35mm | 97m",
      "Car Wash",
      "Sat, Jul 1, 2023 4:00 PM",
      "16:00",
      "1",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/car-wash-1976.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "572A111A-7201-4924-A133-DC42CBA70DAE",
      "P",
      "Evening",
      "",
      "DOC20230701E",
      "Robert Altman | 1975 | DCP | 160m",
      "Nashville",
      "Sat, Jul 1, 2023 7:00 PM",
      "19:00",
      "1",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/nashville-1975.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "D6A9D413-22DB-4E48-AC52-8FD9A71B6C67",
      "P",
      "Evening",
      "",
      "DOC20230707M",
      "John Ford | 1956 | 35mm | 119m",
      "The Searchers",
      "Fri, Jul 7, 2023 4:00 PM",
      "16:00",
      "7",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "https://tickets.uchicago.edu/Online/default.asp?doWork::WScontent::loadArticle=Load&BOparam::WScontent::loadArticle::article_id=5B46B67B-FA8D-4216-AAAE-5EF756228310&BOparam::WScontent::loadArticle::context_id=D6A9D413-22DB-4E48-AC52-8FD9A71B6C67",
      "",
      "/content/Images/the-searchers-1956.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "8487B4C1-76BC-4E7C-B926-227D5F3A07D3",
      "P",
      "Evening",
      "",
      "DOC20230707E",
      "Frank Pierson | 1976 | DCP | 139m",
      "A Star Is Born",
      "Fri, Jul 7, 2023 7:00 PM",
      "19:00",
      "7",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/a-star-is-born-1976.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "2C2D693D-0E94-4AD3-ADA6-E00F5A229415",
      "P",
      "Evening",
      "",
      "DOC20230708M",
      "Frank Pierson | 1976 | DCP | 139m",
      "A Star Is Born",
      "Sat, Jul 8, 2023 4:00 PM",
      "16:00",
      "8",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/a-star-is-born-1976.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "5099868A-972E-4D2D-AC72-013A80917499",
      "P",
      "Evening",
      "",
      "DOC20230708E",
      "John Ford | 1956 | 35mm | 119m",
      "The Searchers",
      "Sat, Jul 8, 2023 7:00 PM",
      "19:00",
      "8",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/the-searchers-1956.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "03E9A5AC-12E9-42DB-96AB-E1B77B35A7B8",
      "P",
      "Evening",
      "",
      "DOC20230714",
      "Alan Rudolph | 1976 | Digital | 106m",
      "Welcome to L.A.",
      "Fri, Jul 14, 2023 7:00 PM",
      "19:00",
      "14",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/welcome-to-la-1976.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "E7FA8C23-49B7-4B25-961C-7DE98BF6668A",
      "P",
      "Evening",
      "",
      "DOC20230715",
      "Alan Rudolph | 1976 | Digital | 106m",
      "Welcome to LA",
      "Sat, Jul 15, 2023 4:00 PM",
      "16:00",
      "15",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/welcome-to-la-1976.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "FA70990D-3815-4375-8E96-8FB6C15A6AEC",
      "P",
      "Evening",
      "",
      "DOC20230721M",
      "Vincente Minnelli | 1944 | 35mm | 113m",
      "Meet Me in St. Louis",
      "Fri, Jul 21, 2023 4:00 PM",
      "16:00",
      "21",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/meet-me-in-st-louis-1944.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "D82B753B-5652-4635-AB5C-4CA4159DE83D",
      "P",
      "Evening",
      "",
      "DOC20230721E",
      "Russ Meyer | 1970 | DCP | 109m",
      "Beyond the Valley of the Dolls",
      "Fri, Jul 21, 2023 7:00 PM",
      "19:00",
      "21",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/beyond-the-valley-of-the-dolls-1970.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "C0B5BE27-9C48-475C-8516-82D54CDF6E77",
      "P",
      "Evening",
      "",
      "DOC20230722M",
      "Russ Meyer | 1970 | DCP | 109m",
      "Beyond the Valley of the Dolls",
      "Sat, Jul 22, 2023 4:00 PM",
      "16:00",
      "22",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/beyond-the-valley-of-the-dolls-1970.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "CC2F20D7-E879-4976-906F-64AAB0209357",
      "P",
      "Evening",
      "",
      "DOC20230722E",
      "Vincente Minnelli | 1944 | 35mm |&nbsp;113m",
      "Meet Me in St. Louis",
      "Sat, Jul 22, 2023 7:00 PM",
      "19:00",
      "22",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/meet-me-in-st-louis-1944.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "6BAAEE27-3BBC-42EC-A890-45BE3E939C55",
      "P",
      "Evening",
      "",
      "DOC20230728M",
      "Reginald Barker | 1926 | 35mm | 70m",
      "The Flaming Forest",
      "Fri, Jul 28, 2023 4:00 PM",
      "16:00",
      "28",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/the-flaming-forest-1926.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "52C5E3BC-6C0A-4B88-8E20-BE8CE1DEAFA9",
      "P",
      "Evening",
      "",
      "DOC20230728E",
      "Frank Perry | 1972 | 35mm | 99m",
      "Play It As It Lays",
      "Fri, Jul 28, 2023 7:00 PM",
      "19:00",
      "28",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/play-it-as-it-lays-1972.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "C6C4F24A-84AF-4D30-8896-28F4CDED38CC",
      "P",
      "Evening",
      "",
      "DOC20230729M",
      "Frank Perry | 1972 | 35mm | 99m",
      "Play It As It Lays",
      "Sat, Jul 29, 2023 4:00 PM",
      "16:00",
      "29",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/play-it-as-it-lays-1972.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "E5DB43D8-3E87-486A-996A-4C6C1A90FFA6",
      "P",
      "Evening",
      "",
      "DOC20230729E",
      "Reginald Barker | 1926 | 35mm | 70m",
      "The Flaming Forest",
      "Sat, Jul 29, 2023 7:00 PM",
      "19:00",
      "29",
      "6",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/the-flaming-forest-1926.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "42939F3B-150A-434C-B1DB-68EF1AD246DF",
      "P",
      "Evening",
      "",
      "DOC20230804M",
      "Noel Smith | 1925 | 35mm | 74m",
      "Clash of the Wolves",
      "Fri, Aug 4, 2023 4:00 PM",
      "16:00",
      "4",
      "7",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/clash-of-the-wolves-1925.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "22666EE9-8AC2-4156-9B4E-48BE8626BC4C",
      "P",
      "Evening",
      "",
      "DOC20230804E",
      "John Boorman | 1967 | DCP | 92m",
      "Point Blank",
      "Fri, Aug 4, 2023 7:00 PM",
      "19:00",
      "4",
      "7",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/point-blank-1967.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "EFE529CF-49A4-4B33-BF53-9A673ED0AE58",
      "P",
      "Evening",
      "",
      "DOC20230805M",
      "John Boorman | 1967 | DCP | 92m",
      "Point Blank",
      "Sat, Aug 5, 2023 4:00 PM",
      "16:00",
      "5",
      "7",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/point-blank-1967.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "4F4F6223-07E8-42DF-B1BD-3645C2B48C4C",
      "P",
      "Evening",
      "",
      "DOC20230805E",
      "Noel Smith | 1925 | 35mm | 74m",
      "Clash of the Wolves",
      "Sat, Aug 5, 2023 7:00 PM",
      "19:00",
      "5",
      "7",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/clash-of-the-wolves-1925.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "F54042DE-9031-4614-9610-9AA98AE4E1C5",
      "P",
      "Evening",
      "",
      "DOC20230811M",
      "Frank Lloyd | 1923 | 35mm | 105m",
      "Within the Law",
      "Fri, Aug 11, 2023 4:00 PM",
      "16:00",
      "11",
      "7",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/within-the-law-1923.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "45D33CEE-B291-4B3D-9904-A1A85215112D",
      "P",
      "Evening",
      "",
      "DOC20230811E",
      "Quentin Tarantino | 2019 | 35mm | 160m",
      "Once Upon a Time... in Hollywood",
      "Fri, Aug 11, 2023 7:00 PM",
      "19:00",
      "11",
      "7",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/once-upon-a-time-in-hollywood-2019.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "DA3F7BD4-1FF9-416C-8701-D1D71D839EEE",
      "P",
      "Evening",
      "",
      "DOC20230812M",
      "Quentin Tarantino | 2019 | 35mm | 160m",
      "Once Upon a Time... in Hollywood",
      "Sat, Aug 12, 2023 4:00 PM",
      "16:00",
      "12",
      "7",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/once-upon-a-time-in-hollywood-2019.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ],
    [
      "909F7A26-0197-4A57-97A9-2AE53FDC16FC",
      "P",
      "Evening",
      "",
      "DOC20230812E",
      "Frank Lloyd | 1923&nbsp; | 35mm| 105m",
      "Within the Law",
      "Sat, Aug 12, 2023 7:00 PM",
      "19:00",
      "12",
      "7",
      "2023",
      "",
      "",
      "S",
      "E",
      "160",
      "Doc Films",
      "",
      "",
      "/content/Images/within-the-law-1923.jpg",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      [
        "1",
        "3"
      ],
      [
        "1",
        "3"
      ],
      "1212 E 59th St",
      "Chicago",
      "US-IL",
      "60637",
      "US",
      "",
      "",
      "66924321-D3CD-4EED-AFAB-D4714596CA69",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "3rd Floor Theater, Ida Noyes Hall",
      "UCArts",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "general admission",
      "Doc Films",
      "$5.00",
      "$5.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "Public",
      "",
      "",
      ""
    ]
  ],
  "searchFilters": [
    {
      "name": "object_type_filter",
      "label": "Type Filter",
      "className": "objectTypeFilterList",
      "clearFilterLabel": "Clear Type Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "month_filter",
      "label": "Month Filter",
      "className": "monthFilterList",
      "clearFilterLabel": "Clear Month Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "city_filter",
      "label": "City Filter",
      "className": "cityFilterList",
      "clearFilterLabel": "Clear City Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "venue_filter",
      "label": "Venue Filter",
      "className": "venueFilterList",
      "clearFilterLabel": "Clear Venue Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "category_filter",
      "label": "Category Filter",
      "className": "categoryFilterList",
      "clearFilterLabel": "Clear Category Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "organization_short_description_filter",
      "label": "Organization Filter",
      "className": "organizationShortDescriptionFilterList",
      "clearFilterLabel": "Clear Organization Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter1",
      "label": "Filter 1",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter2",
      "label": "Filter 2",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter3",
      "label": "Filter 3",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter4",
      "label": "Filter 4",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter_parent1",
      "label": "Filter Parent 1",
      "className": "customFilterParentList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "filter_parent2",
      "label": "Filter Parent 2",
      "className": "customFilterParentList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "multifilter1",
      "label": "Multi Filter 1",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    },
    {
      "name": "multifilter2",
      "label": "Multi Filter 2",
      "className": "customFilterList",
      "clearFilterLabel": "Clear Filter",
      "selectedValue": "",
      "values": []
    }
  ],
  "searchCalendarFilters": [
    {
      "name": "calendar_days",
      "label": "Calendar Days",
      "className": "dayFilterList",
      "clearFilterLabel": "Clear Day Filter",
      "selectedValue": "",
      "values": [
        [
          "2023-06-09T00:00:00.000",
          "1"
        ],
        [
          "2023-06-29T00:00:00.000",
          "1"
        ],
        [
          "2023-07-14T00:00:00.000",
          "1"
        ],
        [
          "2023-07-15T00:00:00.000",
          "1"
        ],
        [
          "2023-06-23T00:00:00.000",
          "2"
        ],
        [
          "2023-06-24T00:00:00.000",
          "2"
        ],
        [
          "2023-06-30T00:00:00.000",
          "2"
        ],
        [
          "2023-07-01T00:00:00.000",
          "2"
        ],
        [
          "2023-07-07T00:00:00.000",
          "2"
        ],
        [
          "2023-07-08T00:00:00.000",
          "2"
        ],
        [
          "2023-07-21T00:00:00.000",
          "2"
        ],
        [
          "2023-07-22T00:00:00.000",
          "2"
        ],
        [
          "2023-07-28T00:00:00.000",
          "2"
        ],
        [
          "2023-07-29T00:00:00.000",
          "2"
        ],
        [
          "2023-08-04T00:00:00.000",
          "2"
        ],
        [
          "2023-08-05T00:00:00.000",
          "2"
        ],
        [
          "2023-08-11T00:00:00.000",
          "2"
        ],
        [
          "2023-08-12T00:00:00.000",
          "2"
        ]
      ]
    }
  ],
  "searchLabels": {
    "performances": "Events",
    "date": "Date",
    "unavailable_message": "Not Available",
    "sold_out_message": "Sold Out!",
    "on_sale_message": "On sale",
    "to_be_determined_message": "TBD",
    "next": "»",
    "previous": "«",
    "next_month": "Next month",
    "previous_month": "Previous month",
    "avail_excellent": "Excellent",
    "avail_good": "Good",
    "avail_limited": "Limited",
    "avail_sold_out": "Sold Out",
    "no_results_message": "We're sorry, there are no events matching your search.",
    "promo_item": "This item is available with a promocode",
    "buy_seats_message": "Tickets",
    "buy_bundle_message": "Buy",
    "buy_item_message": "Buy",
    "pageNext": "Next",
    "pagePrev": "Previous",
    "buy_gift_message": "Donate",
    "buy_storedvalueitem_message": "Buy",
    "upsell_seats_message": "Upgrade",
    "upsell_bundle_message": "Upgrade",
    "upsell_item_message": "Upgrade",
    "upsell_gift_message": "Upgrade",
    "upsell_storedvalueitem_message": "Upgrade",
    "upsell_popup_title": "Interested in Upgrading?",
    "addon_seats_message": "Select",
    "addon_bundle_message": "Select",
    "addon_item_message": "Select",
    "addon_gift_message": "Select",
    "addon_storedvalueitem_message": "Select",
    "exchange_seats_message": "Select",
    "exchange_bundle_message": "Select",
    "exchange_item_message": "Select",
    "exchange_gift_message": "Select",
    "exchange_storedvalueitem_message": "Select",
    "describe_seats_message": "%action, %name, %datetime",
    "describe_bundle_message": "%action, %name",
    "describe_item_message": "%action, %name",
    "describe_gift_message": "%action, %name",
    "describe_storedvalueitem_message": "%action, %name",
    "describe_article_message": "%action, %name",
    "see_events_for_date": "See events for %m %d",
    "select_your_time": "Please select your time",
    "view_article_message": "View",
    "price_title": "Price",
    "pagination": "Pagination",
    "availability_title": "Availability",
    "active_promo_codes": "Active promotions:",
    "promo_code_item_title": "This item is available with a promocode",
    "has_promo_code": "false",
    "brand_path": "../../content/images/branding/"
  },
  "searchSUMO": {
    "availability_access": "true",
    "mapSelect_access": "true"
  },
  "pagination": {
    "current_page": "1",
    "page_size": "80",
    "total_pages": "1"
  },
  "loginLabels": {
    "pageTarget": "maintainAccount.asp",
    "loginBoxClass": "login-required",
    "forgotPassword": "true",
    "formLoginName": "",
    "accountLogin": "true"
  },
  "contextId": "",
  "articleId": "5B46B67B-FA8D-4216-AAAE-5EF756228310",
  "articleSearchId": "",
  "salesType": "P",
  "sToken": "1,efc391cf,64912efe,BFD1C0DA-569A-44C9-8927-2B66CB71E02B,bgO06PvVKCINWAnaMwSOwB3vsiI="
}


if __name__ == '__main__':
    main()

